<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>c06c65d1-3b76-451c-95c6-de144230decf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.o-layout__item.u-width-12 > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='js-IPDE']/main/section/div/section[2]/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>68fb7489-16bf-4392-987f-bdb7337e56ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>graphics/00000001/pos_topbanner_INPROCESS.jpg</value>
      <webElementGuid>2d4a5b38-dc56-4b29-888c-77f53d0a8c80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-IPDE&quot;)/main[@class=&quot;o-wrapper&quot;]/section[@class=&quot;o-layout o-layout--main-content&quot;]/div[@class=&quot;o-layout__item u-width-12&quot;]/section[@class=&quot;o-layout&quot;]/div[@class=&quot;o-layout__item u-width-12&quot;]/img[1]</value>
      <webElementGuid>bf23d153-9fb9-468e-a4bc-422570127dd9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='js-IPDE']/main/section/div/section[2]/div/img</value>
      <webElementGuid>61f9b24a-aaf1-45ea-8d8d-3803c3c489b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>662d604e-5592-46cb-94d3-f8de834a377d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'graphics/00000001/pos_topbanner_INPROCESS.jpg']</value>
      <webElementGuid>1bdd9707-e5e2-4a1f-ad99-a8a000af163c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
