<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>76a6ae68-4409-4146-beec-fe6b9d512f2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Project OpenSquish banner&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='js-OSVC']/main/section/div/section/div[3]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9115b0a1-290d-4c3c-a3e3-695599ee865b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>graphics/00000001/pos_banner_wide.png</value>
      <webElementGuid>07b49c69-d48e-438a-8612-bd565ecc0b43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Project OpenSquish banner</value>
      <webElementGuid>6cbab0e4-4b5d-45dc-a2bb-b5adc0cc39ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Project OpenSquish banner</value>
      <webElementGuid>c31478eb-1293-479c-b49d-7f18495d2da8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-OSVC&quot;)/main[@class=&quot;o-wrapper&quot;]/section[@class=&quot;o-layout o-layout--main-content&quot;]/div[@class=&quot;o-layout__item&quot;]/section[@class=&quot;o-layout&quot;]/div[@class=&quot;o-layout__item u-width-12&quot;]/img[1]</value>
      <webElementGuid>46af3a32-137d-44c2-b1bc-2525bfe23994</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='js-OSVC']/main/section/div/section/div[3]/img</value>
      <webElementGuid>96456042-3c9d-41c1-a3a3-642c1cf203ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Project OpenSquish banner']</value>
      <webElementGuid>7a2bc97a-be60-464f-b823-c2c62d93dad5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/img</value>
      <webElementGuid>16849765-8154-4478-a291-1b8703000924</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'graphics/00000001/pos_banner_wide.png' and @title = 'Project OpenSquish banner' and @alt = 'Project OpenSquish banner']</value>
      <webElementGuid>9c051dca-a9db-470e-adea-348187ade861</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
