<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_SCORE_x-product-list__image</name>
   <tag></tag>
   <elementGuidId>0c411b7c-74d5-4215-a554-199938ac01f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='os_ctgy_item_module']/a/img)[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0e390683-5aa5-4773-8b3c-01e009dc8518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-product-list__image</value>
      <webElementGuid>22513e9e-80e0-400e-98db-f0af1dca0df9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>graphics/00000001/opensquish_gingerbone_man_453010_thumbnail.jpg</value>
      <webElementGuid>761e914e-52df-4526-a56f-8caa922f4883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Squishable Gingerbone Man thumbnail</value>
      <webElementGuid>2d31e8ff-2226-4fc0-a928-fa4b40a9152b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-OSVC&quot;)/main[@class=&quot;o-wrapper&quot;]/section[@class=&quot;o-layout o-layout--main-content&quot;]/div[@class=&quot;o-layout__item&quot;]/section[@class=&quot;o-layout&quot;]/div[@class=&quot;o-layout__item u-width-12&quot;]/section[@class=&quot;o-layout&quot;]/section[@class=&quot;o-layout&quot;]/div[@class=&quot;o-layout__item u-width-12&quot;]/section[@class=&quot;o-layout u-grids-2 u-grids-3--m u-grids-4--l x-product-list&quot;]/div[@id=&quot;os_ctgy_item_module&quot;]/a[@class=&quot;u-block x-product-list__link&quot;]/img[@class=&quot;x-product-list__image&quot;]</value>
      <webElementGuid>1c03b0bf-1571-4c93-be7d-49071efc815c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='os_ctgy_item_module']/a/img)[2]</value>
      <webElementGuid>4a07ca87-7396-4c73-aabe-4ad59b220b03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Squishable Gingerbone Man thumbnail']</value>
      <webElementGuid>eb1b3113-7dc4-4eb8-bb06-900be2a26ca4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div[2]/a/img</value>
      <webElementGuid>0ec3c770-98ae-4a67-9bde-b3aa99cf2a68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'graphics/00000001/opensquish_gingerbone_man_453010_thumbnail.jpg' and @alt = 'Squishable Gingerbone Man thumbnail']</value>
      <webElementGuid>cece6a22-87ac-407f-bc72-fa8a26f3e57c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
