<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SCORE_waiting</name>
   <tag></tag>
   <elementGuidId>d3db3b83-0edd-468e-872c-c200cb1b7545</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;waiting&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='waiting']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3963a040-b5e4-4625-b9d0-ad4d6e32f97f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>fc23fd36-4a5d-4262-affd-bd443141cdda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>waiting</value>
      <webElementGuid>b2dfb848-c5f8-4610-a7f9-8ce1e62d9f64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Go!</value>
      <webElementGuid>00bd3540-5f55-47b0-b801-28387f2d209e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;os_waitlist&quot;)/form[1]/input[7]</value>
      <webElementGuid>51c60d82-4bbc-4ae3-bb3b-6808584e984f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='waiting']</value>
      <webElementGuid>6b74b91b-fe66-49ba-81cb-13a7da8cae1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='os_waitlist']/form/input[7]</value>
      <webElementGuid>df56cf95-a1a3-40d3-8636-0b72cdd41c08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/form/input[7]</value>
      <webElementGuid>d48c634e-c7cc-40b4-926b-c74a4538efac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'waiting']</value>
      <webElementGuid>4111101a-6b7c-4bd0-bf57-62aa368edaf8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
