<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_PARTICIPATE</name>
   <tag></tag>
   <elementGuidId>ec50fb0a-a0a6-4137-b7ab-d78951ca9a60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='js-SFNT']/header/section[3]/div/nav/ul/li[2]/a/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>43ee251d-843c-4eb0-872e-498253a5d112</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PARTICIPATE</value>
      <webElementGuid>e0ad0a7f-c6ac-4d13-996a-0569384b72db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-SFNT&quot;)/header[@class=&quot;o-site-wrapper&quot;]/section[@class=&quot;o-layout u-grids-1 o-site-header__masthead o-wrapper&quot;]/div[@class=&quot;o-layout__hide o-layout__show--l&quot;]/nav[@class=&quot;c-navigation u-text-uppercase x-drop-down-navigation&quot;]/ul[@class=&quot;c-navigation__row x-drop-down-navigation__row&quot;]/li[@class=&quot;nav-item c-navigation__list has-drop-down&quot;]/a[@class=&quot;c-navigation__link&quot;]/div[1]/span[1]</value>
      <webElementGuid>12c999ef-614f-4144-bb2c-5e0c131013d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='js-SFNT']/header/section[3]/div/nav/ul/li[2]/a/div/span</value>
      <webElementGuid>786665f7-ba3f-4d6d-b060-eba638f3331e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shop by Theme'])[1]/following::span[1]</value>
      <webElementGuid>dd7e4e6c-374e-4cfd-aca9-96cfedc852d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Our Stores'])[1]/following::span[1]</value>
      <webElementGuid>7226ceb9-efce-46a6-a6ce-778d1cbfc574</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vote'])[1]/preceding::span[1]</value>
      <webElementGuid>4a050e53-3e07-46d3-9283-7cc53897c7f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vote on New Designs'])[1]/preceding::span[1]</value>
      <webElementGuid>f36fd5fd-6930-4c32-b1fb-38c91c655688</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PARTICIPATE']/parent::*</value>
      <webElementGuid>0e9172c6-98d8-4d72-a56f-a44b2710e970</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/div/span</value>
      <webElementGuid>ab30d8ab-b85e-439c-b063-566190365476</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'PARTICIPATE' or . = 'PARTICIPATE')]</value>
      <webElementGuid>5bccfe48-08b4-44cf-b24c-003becf40f7f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
