<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SCORE_wait_email</name>
   <tag></tag>
   <elementGuidId>322771c7-0e1a-4878-a033-5f5a61407a61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;wait_email&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='wait_email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>71aeb165-20b7-4598-81da-e4eca5869308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Enter your email address here to join this waiting list</value>
      <webElementGuid>3cb02da9-f74c-4dc5-97b5-7c1b0734514c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>12f06316-e371-4e19-8f08-7e16aa11d412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wait_email</value>
      <webElementGuid>602a9415-6b63-4640-8872-2b382b159189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>this.placeholder=''</value>
      <webElementGuid>3b236737-db91-4d73-969e-432d8aa7f2e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;os_waitlist&quot;)/form[1]/input[6]</value>
      <webElementGuid>2ab9565f-7a6b-4a2c-9e70-afc2c8f4053d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='wait_email']</value>
      <webElementGuid>f2d0996b-3264-4cfd-8a3c-f2997cebf86f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='os_waitlist']/form/input[6]</value>
      <webElementGuid>0ca70258-00ac-4ad3-aabb-ae1b9bb1bbe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/form/input[6]</value>
      <webElementGuid>7a4827d6-203c-46bf-9c2c-e5e48041116b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@title = 'Enter your email address here to join this waiting list' and @type = 'text' and @name = 'wait_email']</value>
      <webElementGuid>49fd0733-b6aa-463e-b8e0-fef54b066be0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
