<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SCORE_waiting</name>
   <tag></tag>
   <elementGuidId>17fdbccf-e010-43c6-b918-565d10071073</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;waiting&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='waiting']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>be68b33b-ae43-4094-958b-862afd835f36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>0c86d050-c5aa-41f9-9b2e-21e3361cb23d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>waiting</value>
      <webElementGuid>077555c1-4663-4948-a8a4-e9d160263718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Go!</value>
      <webElementGuid>30c3eb4b-f9f5-4ed6-8142-83de5203d5dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;os_waitlist&quot;)/form[1]/input[7]</value>
      <webElementGuid>3420daa6-5ed5-4262-808e-76e55e1faae8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='waiting']</value>
      <webElementGuid>5d966e8c-8cad-4217-87ae-ae8d9c75ed07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='os_waitlist']/form/input[7]</value>
      <webElementGuid>16afb62b-bcbb-4cee-8398-1d0bd12c3cde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/form/input[7]</value>
      <webElementGuid>e13086d8-3a38-468c-910a-d15efd25e004</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'waiting']</value>
      <webElementGuid>2fd4d2a0-9d4d-4c7f-96a8-996ac8c808dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
