<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Comfort Food Chocolate Chunk Cookie_main_image</name>
   <tag></tag>
   <elementGuidId>627c76cd-9b32-4e38-a49e-0bac8fc40bbf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#main_image</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='main_image']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>af3dd6f2-568d-4fc7-990b-b4f3b3e5c817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main_image</value>
      <webElementGuid>f2d6e33c-9426-4334-8cdc-cf28c5b86421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>x-product-layout-images__image</value>
      <webElementGuid>143df5da-d632-4be8-a529-cf8dd3418e01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>graphics/00000001/6/comfortfood_chocolate_chunk_cookie.jpg</value>
      <webElementGuid>b828a236-6315-4876-8ede-e5991a168c62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Comfort Food Chocolate Chunk Cookie</value>
      <webElementGuid>67e9a2f0-62d1-4b8a-a75d-d1e6139d0568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Comfort Food Chocolate Chunk Cookie</value>
      <webElementGuid>80a0d680-ffe6-4f90-b953-855974958afc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main_image&quot;)</value>
      <webElementGuid>c88273cf-dda5-4d8f-bfdf-0b6090207ef7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='main_image']</value>
      <webElementGuid>7f5ae98c-6d1c-4308-bf01-d7b25a242d58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='js-PROD']/main/section/div/div/div/section/div/div/img</value>
      <webElementGuid>8cf3aabb-6216-4cab-90d7-ae195e843886</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Comfort Food Chocolate Chunk Cookie']</value>
      <webElementGuid>7ac73b3f-0803-43a0-9e8b-a681353b425d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>ede063e9-d448-49f3-8c5b-2e139af3c8de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'main_image' and @src = 'graphics/00000001/6/comfortfood_chocolate_chunk_cookie.jpg' and @alt = 'Comfort Food Chocolate Chunk Cookie' and @title = 'Comfort Food Chocolate Chunk Cookie']</value>
      <webElementGuid>3ce0a796-54b0-48d3-8ac9-0258e54726c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
