<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_PARTICIPATE_u-icon-chevron-down</name>
   <tag></tag>
   <elementGuidId>fca539d3-e2b5-4132-a91c-9387b89ba647</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='js-SFNT']/header/section[3]/div/nav/ul/li[2]/a/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6d243b3a-8319-4266-a2c3-dd561df74305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>u-icon-chevron-down</value>
      <webElementGuid>0e88b80d-c4f0-49f9-b7ac-4606417b06c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-SFNT&quot;)/header[@class=&quot;o-site-wrapper&quot;]/section[@class=&quot;o-layout u-grids-1 o-site-header__masthead o-wrapper&quot;]/div[@class=&quot;o-layout__hide o-layout__show--l&quot;]/nav[@class=&quot;c-navigation u-text-uppercase x-drop-down-navigation&quot;]/ul[@class=&quot;c-navigation__row x-drop-down-navigation__row&quot;]/li[@class=&quot;nav-item c-navigation__list has-drop-down&quot;]/a[@class=&quot;c-navigation__link&quot;]/div[1]/div[@class=&quot;chevron&quot;]/div[@class=&quot;u-icon-chevron-down&quot;]</value>
      <webElementGuid>d194bb91-21cc-45b9-af1c-6c102220066a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='js-SFNT']/header/section[3]/div/nav/ul/li[2]/a/div/div/div</value>
      <webElementGuid>c1602290-0aae-40bb-ab6a-184c73d14241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/div/div/div</value>
      <webElementGuid>88f4b6c2-ba5c-4d19-9919-0fbdbe18d30e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
